// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"platform-go/internal/infrastructure/queryservice"
	"platform-go/internal/infrastructure/repository"
	"platform-go/internal/interfaces/controller"
	"platform-go/internal/usecases"
	"testing"
)

// Injectors from wire-test.go:

func TestInitializeControllers(t *testing.T, db *gorm.DB) (*TestHandlerSet, error) {
	userRepository := repository.NewMySQLUserRepository(db)
	userUsecase := usecases.NewUserUsecase(userRepository)
	userQueryService := queryservice.NewUserQueryService(db)
	userController := controller.NewUserController(userUsecase, userQueryService)
	testHandlerSet := &TestHandlerSet{
		Handler: userController,
		DB:      db,
	}
	return testHandlerSet, nil
}

// wire-test.go:

type TestHandlerSet struct {
	Handler *controller.UserController
	DB      *gorm.DB
}
