// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"platform-go/internal/infrastructure/queryservice"
	"platform-go/internal/infrastructure/repository"
	"platform-go/internal/interfaces/controller"
	"platform-go/internal/usecases"
)

// Injectors from wire.go:

func InitializeHandler(db *gorm.DB) *controller.UserController {
	userRepository := repository.NewMySQLUserRepository(db)
	userUsecase := usecases.NewUserUsecase(userRepository)
	userQueryService := queryservice.NewUserQueryService(db)
	userController := controller.NewUserController(userUsecase, userQueryService)
	return userController
}
